// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taskboard.EntityFrameworkCore.Data;

#nullable disable

namespace Taskboard.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(TaskboardDbContext))]
    partial class TaskboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Taskboard.Domain.Entities.AiChatEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.ToTable("AiChatEvents", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.AiChatRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.ToTable("AiChatRuns", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.AiChatThread", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginProjectId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningEffort")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sandbox")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OriginProjectId");

                    b.ToTable("AiChatThreads", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Attachment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "CreatedAt", "Id")
                        .HasDatabaseName("IX_Attachments_Task_Created");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "CreatedAt", "Id")
                        .HasDatabaseName("IX_Comments_Task_Created");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("NextTaskNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkspacePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("_labels")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("labels");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.ProjectSummary", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectSummaries", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Task", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assignee")
                        .HasColumnType("TEXT")
                        .HasColumnName("assignee");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creator");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalOrigin")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitBranch")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Recurrence")
                        .HasColumnType("TEXT")
                        .HasColumnName("recurrence");

                    b.Property<double?>("SortOrder")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadBinding")
                        .HasColumnType("TEXT")
                        .HasColumnName("thread_binding");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkflowId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorktreeBranch")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorktreePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("_labels")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("labels");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("UIX_Tasks_Identifier");

                    b.HasIndex("ExternalSource", "ExternalOrigin", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UIX_Tasks_External");

                    b.HasIndex("ProjectId", "ArchivedAt", "Status", "SortOrder", "CreatedAt")
                        .HasDatabaseName("IX_Tasks_Project_Status_Sort");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.TaskActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "Timestamp", "Id")
                        .HasDatabaseName("IX_TaskActivities_Task_Created");

                    b.ToTable("TaskActivities", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.TaskRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("relation_type");

                    b.Property<string>("SourceTaskId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetTaskId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceTaskId");

                    b.HasIndex("TargetTaskId")
                        .IsUnique()
                        .HasDatabaseName("UIX_TaskRelations_Parent")
                        .HasFilter("relation_type = 'parent'");

                    b.ToTable("TaskRelations", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.WorkflowNode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<double>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("WorkflowNodes", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.WorkflowSequence", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceNodeId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetNodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SourceNodeId");

                    b.HasIndex("TargetNodeId");

                    b.ToTable("WorkflowSequences", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.WorkflowWorkspace", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Workspace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkflowWorkspaces", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.AiChatEvent", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.AiChatThread", null)
                        .WithMany("Events")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.AiChatRun", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.AiChatThread", null)
                        .WithMany("Runs")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.AiChatThread", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("OriginProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.Task", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.Task", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.ProjectSummary", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Task", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.TaskActivity", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.Task", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.TaskRelation", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.Task", null)
                        .WithMany()
                        .HasForeignKey("SourceTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TaskRelations_SourceTask");

                    b.HasOne("Taskboard.Domain.Entities.Task", null)
                        .WithMany()
                        .HasForeignKey("TargetTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TaskRelations_TargetTask");
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.WorkflowNode", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.WorkflowSequence", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taskboard.Domain.Entities.WorkflowNode", null)
                        .WithMany()
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_WorkflowSequences_SourceNode");

                    b.HasOne("Taskboard.Domain.Entities.WorkflowNode", null)
                        .WithMany()
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WorkflowSequences_TargetNode");
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.WorkflowWorkspace", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.AiChatThread", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
