<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Taskboard.Application/Taskboard.Application.csproj" />
    <ProjectReference Include="../Taskboard.EntityFrameworkCore/Taskboard.EntityFrameworkCore.csproj" />
    <ProjectReference Include="../Taskboard.Application.Contracts/Taskboard.Application.Contracts.csproj" />
    <ProjectReference Include="../Taskboard.Integrations/Taskboard.Integrations.csproj" />
    <ProjectReference Include="../Taskboard.Blazor/Taskboard.Blazor.csproj" />
  </ItemGroup>
</Project>
